<<<<<<< HEAD:docker-compose.yml

services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    container_name: dollar-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped

=======

services:
  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    container_name: dollar-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped

>>>>>>> origin/main:Dollar-exchange-rate/docker-compose.yml
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    container_name: dollar-server 
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
    restart: unless-stopped

volumes:
  db_data:
