FROM python:3.12-slim

WORKDIR /app

COPY job_requirements.txt .

RUN pip install --no-cache-dir -r job_requirements.txt

COPY db_access ./db_access

RUN pip install requests

# CMD ["python", "-m", "db_access.jobs.monthly_update"]How to stay thus container running after the script ends?
CMD python -m db_access.jobs.monthly_update || true; tail -f /dev/null
